services:
  config-server:
    image: "gokultmail/config-server:latest"
    container_name: "config-server"
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - relatia
  customer-service:
    image: "gokultmail/customer-service:latest"
    container_name: "customer-service"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - relatia
  notification-service:
    image: "gokultmail/notification-service:latest"
    container_name: "notification-service"
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - relatia
networks:
  relatia:
    driver: bridge