services:
  rabbit:
    extends:
      file: common-config.yaml
      service: network-deploy-service
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_cookie
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  config-server:
    image: "gokultmail/config-server:latest"
    container_name: "config-server"
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  customerdb:
    container_name: customerdb
    environment:
      MYSQL_DATABASE: customerdb
    extends:
      file: common-config.yaml
      service: microservice-db-config

  customer-service:
    extends:
      file: common-config.yaml
      service: microservice-config-server-config
    image: "gokultmail/customer-service:latest"
    container_name: "customer-service"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://customerdb:3306/customerdb"
    depends_on:
      customerdb:
        condition: service_healthy
      config-server:
        condition: service_healthy

  notification-service:
    extends:
      file: common-config.yaml
      service: microservice-config-server-config
    image: "gokultmail/notification-service:latest"
    container_name: "notification-service"
    ports:
      - "9000:9000"

networks:
  relatia:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_logs: